daftarCurated10 = [
"hackertyper.com",
"maze.toys",
"window-swap.com",
"radiooooo.com",
"pointerpointer.com",
"mondrianandme.com",
"boredbutton.com",
"alwaysjudgeabookbyitscover.com",
"ffffidget.com",
"trypap.com",
"smashthewalls.com",
"weirdorconfusing.com",
"thezen.zone",
"creativetechguy.com",
["https://creativetechguy.com/fishfeeder","Fish Feeder"],
"play2048.co",
"screamintothevoid.com",
"29a.ch",
["https://29a.ch/sandbox/2011/neonflames/","Neonflames"],
"patience-is-a-virtue.org",
"endless.horse",
"papertoilet.com",
];
daftarSitus = daftarSitus.concat(daftarCurated10);
