daftarCurated8 = [
"google.com",
"youtube.com",
"amazon.com",
"facebook.com",
"yahoo.com",
"reddit.com",
"en.wikipedia.org",
["https://en.wikipedia.org/wiki/Special:Random", "Wikipedia"],
"ebay.com",
"bing.com",
"netflix.com",
"office.com",
"instructure.com",
"shopify.com",
"twitch.tv",
"cnn.com",
"linkedin.com",
"instagram.com",
"intuit.com",
"nytimes.com",
"chase.com",
];
daftarSitus = daftarSitus.concat(daftarCurated8);
