daftarCurated4 = [
"instagram.com",
"slashdot.org",
"facebook.com",
"web.facebook.com",
"techcrunch.com",
"forbes.com",
"fiverr.com",
"vogue.com",
"trakt.tv",
"avclub.com",
"bbc.com",
"npr.org",
"fastcompany.com",
"store.steampowered.com",
"linkedin.com",
"fark.com",
"mirror.co.uk",
"drudgereport.com",
"businessinsider.com",
"abcnews.go.com",
"pinterest.com",
"newsweek.com",
"forekast.com",
"latimes.com",
"ny1.com",

];
daftarSitus = daftarSitus.concat(daftarCurated4);
